### ISSUE TITLE
Refine approach phase

### ISSUE THREAD

**Issue by pattacini** [robotology/tactile-control#1]
Consider using off-the-shelf components for detecting when the approach is finished.
See for example the [Adaptive Window Polynomial Estimators][1].

[1]: http://wiki.icub.org/iCub/main/dox/html/group__adaptWinPolyEstimator.html

**Comment by pattacini** [comment]
@massimoregoli 
This is a longlasting issue.
@massimoregoli what's the current status?

**Comment by massimoregoli** [comment]
I gave priority to other issues/tasks, considering this a low priority one, but you are right it has been open for too long, in a few days I will work on that.

**Comment by massimoregoli** [comment]
The approach phase is now working using the Adaptive Window Polynomial Estimator.
